-- tips for cards that don't have a rule that explain them
CARD = {
	skip = "CARD_SKIP",
	reverse = "CARD_REVERSE",
	draw2 = "CARD_DRAW_TWO",
	wild = "CARD_WILD",
	draw4 = "CARD_WILD_DRAW_FOUR",
	pawn = "CARD_PAWN",
	bishop = "CARD_BISHOP",
	knight = "CARD_KNIGHT",
	rook = "CARD_ROOK",
	queen = "CARD_QUEEN",
	king = "CARD_KING",
	chest = "CARD_TREASURE",
	down = "CARD_DOWN",
	left = "CARD_LEFT",
	right = "CARD_RIGHT",
	up = "CARD_UP",
	shield = "CARD_SHIELD",
	mix1 = "CARD_MIX1",
	mix2 = "CARD_MIX2",
	mix3 = "CARD_MIX3",
}